name = "DeepBurn"
uuid = "556d5560-0350-4447-924b-0f3e963a26a6"
authors = ["Gert Van den Eynde"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
