name = "Deepburn"
uuid = "27ad6030-87a9-4e8e-b661-335f45a2cf5e"
authors = ["Van den Eynde Gert <gert.van.den.eynde@sckcen.be> and contributors"]
version = "0.1.0"

[compat]
julia = "1.8.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
